markdown: kramdown
pygments: true
permalink: /post/:title

paginate: 10
paginate_path: '/blog/:num'

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil